/* AUTOGENERATED FILE - DO NOT EDIT! */
/* This file is provided by the meta-mender layer. */

#ifndef HEADER_CONFIG_MENDER_DEFINES_H
#define HEADER_CONFIG_MENDER_DEFINES_H

/* Shell variables */
#define MENDER_BOOT_PART_NUMBER 1
#define MENDER_BOOT_PART_NUMBER_HEX 1
#define MENDER_ROOTFS_PART_A_NUMBER 2
#define MENDER_ROOTFS_PART_A_NUMBER_HEX 2
#define MENDER_ROOTFS_PART_B_NUMBER 3
#define MENDER_ROOTFS_PART_B_NUMBER_HEX 3
#define MENDER_UBOOT_STORAGE_INTERFACE "mmc"

#ifdef CONFIG_ROOTFS_EMMC
#  define MENDER_UBOOT_STORAGE_DEVICE 1
#  define MENDER_STORAGE_DEVICE "/dev/mmcblk1"
#  define MENDER_STORAGE_DEVICE_BASE "/dev/mmcblk1p"
#  define MENDER_ROOTFS_PART_A_NAME "/dev/mmcblk1p2"
#  define MENDER_ROOTFS_PART_B_NAME "/dev/mmcblk1p3"
#else
#  define MENDER_UBOOT_STORAGE_DEVICE 0
#  define MENDER_STORAGE_DEVICE "/dev/mmcblk0"
#  define MENDER_STORAGE_DEVICE_BASE "/dev/mmcblk0p"
#  define MENDER_ROOTFS_PART_A_NAME "/dev/mmcblk0p2"
#  define MENDER_ROOTFS_PART_B_NAME "/dev/mmcblk0p3"
#endif

/* BB variables. */
#define MENDER_UBOOT_ENV_STORAGE_DEVICE_OFFSET_1 0x800000
#define MENDER_UBOOT_ENV_STORAGE_DEVICE_OFFSET_2 0x1000000

/* For sanity checks. */
#define MENDER_BOOTENV_SIZE 0x20000

/* Beaglebone Black Debian settings */
#define MENDER_BOOT_KERNEL_TYPE "bootz"
#define MENDER_KERNEL_NAME "dummy"
#define MENDER_DTB_NAME "dummy"
#define MENDER_UBOOT_PRE_SETUP_COMMANDS "run findfdt; run init_console;"
#define MENDER_UBOOT_POST_SETUP_COMMANDS "if load ${mender_uboot_root} ${loadaddr} /boot/${bootenvfile}; then env import -t ${loadaddr} ${filesize}; fi; setenv mender_dtb_name dtbs/${uname_r}/${fdtfile}; setenv mender_kernel_name vmlinuz-${uname_r}; setenv bootargs ${bootargs} console=${console} ${optargs} ${cape_disable} ${cape_enable} ${cape_uboot} rootfstype=${mmcrootfstype} ${uboot_detected_capes} ${cmdline} quiet"

#endif /* !HEADER_CONFIG_MENDER_DEFINES_H */
